### ISSUE TITLE
Can i pretrain the model ？

### ISSUE THREAD

**Issue by SnowBoy0215** [universal-ie/UIE#11]
Can i pretrain the model ？ why do i feel that the data processing part of the code is incomplete? I even cant follw the readme.

**Comment by luyaojie** [comment]
Hi, the pre-training code will be released soon, I will add some demonstrations.

And which part in the data processing part is incomplete or difficult to understand?

You can email [me](yaojie2017@iscas.ac.cn) for details if you like.

**Comment by SnowBoy0215** [comment]
Ok, thank you for your reply.
