### ISSUE TITLE
The SSI difference between  train and predict

### ISSUE THREAD

**Issue by xinjicong** [universal-ie/UIE#14]
想问一下，在训练时候text前面加上的SSI是每条样本中的SSI，predict的时候是所有SSI的拼接？
如果SSI数量过多，预测的时候需要进行SSI划分，分开预测？

**Comment by luyaojie** [comment]
如果有问题，欢迎再次打开Issue，或者[给我发邮件](mailto:yaojie2017@iscas.ac.cn)
If you have any further questions, please open the Issue again or [email me](mailto:yaojie2017@iscas.ac.cn)
