### ISSUE TITLE
训练数据中的record是如何得到的？

### ISSUE THREAD

**Issue by SnowBoy0215** [universal-ie/UIE#15]
陆博士，我想问一下您，训练数据中的"record": "<extra_id_0> <extra_id_0> geographical social political是如何得到的呢？

**Comment by luyaojie** [comment]
在数据处理阶段，将Entity、Relation、Event 转成 spot-asoc的形式，然后转成对应的 Record 字符串。

https://github.com/universal-ie/UIE/blob/7ca348cd12cd0e9d2c39c9b217efeebf70cee718/dataset_processing/universal_ie/generation_format/text2spotasoc.py#L176

**Comment by SnowBoy0215** [comment]
还有一点不太明白，恳请解答，# Entity Types for converting SEL to Record 这句话中的"Record"指的是DATASETS.md中的"spot_asoc"吗？也就是说"spot_asoc"是最终想要的结果，可是我复现代码 在preds_record.txt里生成的好像不太一样。
