### ISSUE TITLE
where is the training code？

### ISSUE THREAD

**Issue by xk503775229** [universal-ie/UIE#21]
Why didn't I see the training code？？？

**Comment by luyaojie** [comment]
Hi,

? What part of the training code?

Pre-training: https://github.com/universal-ie/UIE/blob/main/run_uie_pretrain.py 
Fine-tuning: https://github.com/universal-ie/UIE/blob/main/run_uie_finetune.py

**Comment by xk503775229** [comment]
oh, I got it 
really appreciate your help！
