### ISSUE TITLE
如何启动GPU运行

### ISSUE THREAD

**Issue by xajh910** [universal-ie/UIE#25]
按照Requirements安装python3.8/pytorch1.8/cuda11.1显示版本不匹配，使用其他版本识别不到GPU

**Comment by luyaojie** [comment]
pip 命令中多了一个 `-y` 已经修改，我这边测试使用 pip 安装可以正常使用 。
但应该和您遇到的问题不同。

可以提供更加详细的信息吗，例如`nvidia-smi` 以及显示不匹配的报错信息？

我的环境
```
 $ nvidia-smi
Fri Jun 17 11:46:58 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1
```

**Comment by xajh910** [comment]
您好，感谢回复。


    报错内容是：OSError: /opt/conda/lib/python3.8/site-packages/torch_scatter/_version_cuda.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_
我网上查出错原因是显示pytorch版本和cuda不一致。版本我看和您git上写的是一致的。我用您git上的安装方式，和直接从官网安装whl文件都试了不行。
       
















在 2022-06-17 11:48:47，"Roger" ***@***.***> 写道：

pip 命令中多了一个 -y 已经修改，我这边测试使用 pip 安装可以正常使用 。
但应该和您遇到的问题不同。

可以提供更加详细的信息吗，例如nvidia-smi 以及显示不匹配的报错信息？

我的环境

 $ nvidia-smi

Fri Jun 17 11:46:58 2022

+-----------------------------------------------------------------------------+

| NVIDIA-SMI 455.23.05    Driver Version: 455.23.05    CUDA Version: 11.1

**Comment by luyaojie** [comment]
看conda位置是在默认的/opt。

能否尝试一下conda create 一个新环境来安装，有可能原环境中包含一些已安装的包有冲突。

**Comment by xajh910** [comment]
done
