### ISSUE TITLE
中文事件数据的预处理

### ISSUE THREAD

**Issue by xxllp** [universal-ie/UIE#28]
是否有中文duee 这些数据上处理成训练数据的代码

**Comment by xxllp** [comment]
我还有个疑问 这个模型是否可以能生成一些不在文本里面的结果

**Comment by luyaojie** [comment]
> 我还有个疑问 这个模型是否可以能生成一些不在文本里面的结果

可以的，但是应该要求训练集中也有 不在文本里面的文本块

**Comment by xxllp** [comment]
> > 我还有个疑问 这个模型是否可以能生成一些不在文本里面的结果
> 
> 可以的，但是应该要求训练集中也有 不在文本里面的文本块

这样怎么标span的起始结束位置呢  还是代码哪里需要改下

**Comment by luyaojie** [comment]
这个得看你的需求是什么，为什么要生成不在文本里面的结果？

**Comment by xxllp** [comment]
我遇到个新问题 新训练个数据集 预测的结果都是<extra_id_0><extra_id_1>,完全都是空 （80%），但是label应该都是有的
评估的指标参考如下  这种是哪里有问题吗？

```
 epoch = 30.0
eval_asoc-F1 = 84.8485
eval_asoc-P = 84.0
eval_asoc-R = 85.7143
eval_asoc-gold = 294.0
eval_asoc-pred = 300.0
eval_asoc-tp = 252.0
eval_gen_len = 10.8574
eval_gold_tree = 596
eval_loss = 0.722
eval_ordered-record-F1 = 53.3333
eval_ordered-record-P = 53.3333
eval_ordered-record-R = 53.3333
eval_ordered-record-gold = 90.0
eval_ordered-record-pred = 90.0
eval_ordered-record-tp = 48.0
eval_overall-F1 = 184.8485
eval_pred_tree = 90
eval_record-F1 = 53.3333
eval_record-P = 53.3333
eval_record-R = 53.3333
eval_record-gold = 90.0
eval_record-pred = 90.0
eval_record-tp = 48.0
eval_runtime = 33.1701
eval_samples_per_second = 17.968
eval_spot-F1 = 100.0
eval_spot-P = 100.0
eval_spot-R = 100.0
eval_spot-gold = 90.0
eval_spot-pred = 90.0
eval_spot-tp = 90.0
eval_well-formed = 596

```

**Comment by xxllp** [comment]
> 这个得看你的需求是什么，为什么要生成不在文本里面的结果？

主要是我直接抽取里面的文本后面还需要后处理  但是想直接出来结果 ，可能是新的结果是原始文本上面做了一些修改或者顺序变了

**Comment by xxllp** [comment]
我这边某个数据集 最终的预测结果里面空占比有点大 这种是因为啥原因导致的~~~

**Comment by luyaojie** [comment]
1. 输入文本太长导致没有信息输入到模型中。可以尝试扩大source的max length
2. 有可能是数据太少，复例太多导致学骗了，可以尝试采样复例比例。

**Comment by luyaojie** [comment]
> 主要是我直接抽取里面的文本后面还需要后处理 但是想直接出来结果 ，新的结果类似是在原始文本上面做了一些增删改的操作

可以直接拿目标端需要抽取的结果作为spot和asoc，看看seq2seq的生成效果。

**Comment by xxllp** [comment]
数据集文本不是很长 平均300不到，数据量也有好几千了

**Comment by xxllp** [comment]
还有个问题：如果事件抽取的是无触法词这种，这种是否只是数据里面改下就行，比如trigger 默认为0 还是啥

**Comment by luyaojie** [comment]
现在代码不支持直接做无触发词，因为结构需要生成trigger作为spot。

如果真的需要，可以尝试一下在输入的文本标记”伪触发词“或者在文本中添加事件类别的名称作为文本中的触发词。

**Comment by xxllp** [comment]
还遇到个奇怪的问题 这个预测的论元有些明显过长（20字以上）这个是不是预测的offset哪里有bug

**Comment by luyaojie** [comment]
目前仓库中的fix unk 是论文中针对英文使用的，面向中文可能不是最优的。

**Comment by xxllp** [comment]
soga~~~好吧我自己想下咋处理

**Comment by xxllp** [comment]
我还有个想法：对于一个文本 是否可以用这个模型同时做 两个任务，比如实体识别+关系抽取  或者是关系抽取+事件抽取
