### ISSUE TITLE
uie-char-small是在什么数据集上预训练的？

### ISSUE THREAD

**Issue by zdgithub** [universal-ie/UIE#30]
请问下中文版的uie-char-small是在什么数据集上预训练的？

**Comment by luyaojie** [comment]
用了两种远距离监督的文本-结构数据：一种是百科的链接数据，另一种是三元组和文本远距离监督的对齐数据。

**Comment by xxllp** [comment]
后面有没有开放更大中文模型的可能

**Comment by luyaojie** [comment]
uie-char-small主要是作为CCKS的比赛基线使用，未来可能会考虑开放。

**Comment by zdgithub** [comment]
好的，感谢！
