### ISSUE TITLE
完全按照readme执行时出现如下错误：

### ISSUE THREAD

**Issue by Shajiu** [universal-ie/UIE#31]
WARNING - __main__ - process rank:-1 device:cuda 0 n_gpu:2 distributed training:false ,16-bits training False
然后没有任何反应停留在此，这个怎么处理哇~

**Comment by luyaojie** [comment]
你好，请问能提供一下详细的执行命令和环境吗？如果太长可以上传一个log文件。

目前看起来卡住的原因可能是使用多卡的分布式相关问题

`n_gpu:2` 应该是使用了两张GPU，默认的README 中的卡数应该是1张或者4张。
我这边在4卡的机器上运行单卡程序log如下，然后会正常运行。
`06/29/2022 10:50:58 - WARNING - __main__ -   Process rank: -1, device: cuda:0, n_gpu: 1distributed training: False, 16-bits training: False`
所以想看看是不是环境配置的问题。

看您在其他几个 issue 也回复提了问题，提供一下环境和命令可以帮助更好地定位问题。

**Comment by luyaojie** [comment]
refer to #32
