### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by Shajiu** [universal-ie/UIE#34]
我将把”CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES} ${run_command} run_uie_finetune.py \“注释了，并且改为”CUDA_VISIBLE_DEVICES=”0“ python  run_uie_finetune.py \“,但是我还是出现了如下问题啊：

**Comment by luyaojie** [comment]
我们回上一个issue 讨论吧 https://github.com/universal-ie/UIE/issues/32 ，一直新开issue 追踪比较困难。

**Comment by luyaojie** [comment]
另外，冒号后的都没有信息，请问是截图了吗？
