### ISSUE TITLE
uie/seq2seq/constrained_seq2seq.py 文件中，ConstraintSeq2SeqTrainer 类的41-42行 self.label_smoother是不是没有指定？

### ISSUE THREAD

**Issue by boy56** [universal-ie/UIE#4]

**Comment by luyaojie** [comment]
是的 UIE的实验中都没有使用 label_smoothing。

**Comment by boy56** [comment]
> 是的 UIE的实验中都没有使用 label_smoothing。

我看您在Text2Event的工作中使用了这部分，想麻烦问下您在做UIE这部分实验的时候为啥没再继续用了啊，是它的作用不明显嘛还是有别的一些原因？

**Comment by boy56** [comment]
> 论文主要想关注基础模型的性能，所以一开始做实验就没有额外添加，后面也就没有针对 Label smoothing 开展实验。

了解了，谢谢您！
