### ISSUE TITLE
预训练部分代码

### ISSUE THREAD

**Issue by xxllp** [universal-ie/UIE#5]
感谢作者开源的代码  想了解下做预训练的这块代码有demo 吗 谢谢~~

**Comment by luyaojie** [comment]
谢谢关注，会有相关样例的。最近比较忙碌，后续会陆续更新。

**Comment by xxllp** [comment]
大佬 感谢回答 还有个问题 ~~百度 统一信息抽取的比赛 里面提供的中文预训练模型 说用远程监督打标的数据  这个用的是知识图谱的来打标的吗  有标记的数据量大概有多少 哈
