### ISSUE TITLE
中文事件抽取数据运行问题

### ISSUE THREAD

**Issue by xxllp** [universal-ie/UIE#8]
你好 我这边用一个中文数据运行会报错 这块是否是数据格式的问题  

样例数据
{
  "text": "巨人网络表决通过增持巨堃网络议案 3成中小投资者投反对票\n原标题：巨人网络(18.030,-0.52,-2.80%)表决通过增持巨堃网络议案 3成中小投资者投反对票    来源：中国网科技\n中国网科技10月9日讯 巨人网络今日发布2019年第一次临时大会决议称，《关于与关联方共同增资上海巨堃网络科技有限公司暨关联交易的议案》获得出席股东大会的股东所持(代表)有效表决权股份总数 1/2 以上通过。\n其中，同意 2,616,017 股，占出席会议中小股东所持股份的 69.8220%；反对 1,130,675 股，占出席会议中小股东所持股份的 30.1780%；弃权 0 股。",
  "tokens": [
    "巨",
    "人",
    "网",
    "络",
    "表",
    "决",
    "通",
    "过",
    "增",
    "持",
    "巨",
    "堃",
    "网",
    "络",
    "议",
    "案",
    " ",
    "3",
    "成",
    "中",
    "小",
    "投",
    "资",
    "者",
    "投",
    "反",
    "对",
    "票",
    "\n",
    "原",
    "标",
    "题",
    "：",
    "巨",
    "人",
    "网",
    "络",
    "(",
    "1",
    "8",
    ".",
    "0",
    "3",
    "0",
    ",",
    "-",
    "0",
    ".",
    "5",
    "2",
    ",",
    "-",
    "2",
    ".",
    "8",
    "0",
    "%",
    ")",
    "表",
    "决",
    "通",
    "过",
    "增",
    "持",
    "巨",
    "堃",
    "网",
    "络",
    "议",
    "案",
    " ",
    "3",
    "成",
    "中",
    "小",
    "投",
    "资",
    "者",
    "投",
    "反",
    "对",
    "票",
    " ",
    " ",
    " ",
    " ",
    "来",
    "源",
    "：",
    "中",
    "国",
    "网",
    "科",
    "技",
    "\n",
    "中",
    "国",
    "网",
    "科",
    "技",
    "1",
    "0",
    "月",
    "9",
    "日",
    "讯",
    " ",
    "巨",
    "人",
    "网",
    "络",
    "今",
    "日",
    "发",
    "布",
    "2",
    "0",
    "1",
    "9",
    "年",
    "第",
    "一",
    "次",
    "临",
    "时",
    "大",
    "会",
    "决",
    "议",
    "称",
    "，",
    "《",
    "关",
    "于",
    "与",
    "关",
    "联",
    "方",
    "共",
    "同",
    "增",
    "资",
    "上",
    "海",
    "巨",
    "堃",
    "网",
    "络",
    "科",
    "技",
    "有",
    "限",
    "公",
    "司",
    "暨",
    "关",
    "联",
    "交",
    "易",
    "的",
    "议",
    "案",
    "》",
    "获",
    "得",
    "出",
    "席",
    "股",
    "东",
    "大",
    "会",
    "的",
    "股",
    "东",
    "所",
    "持",
    "(",
    "代",
    "表",
    ")",
    "有",
    "效",
    "表",
    "决",
    "权",
    "股",
    "份",
    "总",
    "数",
    " ",
    "1",
    "/",
    "2",
    " ",
    "以",
    "上",
    "通",
    "过",
    "。",
    "\n",
    "其",
    "中",
    "，",
    "同",
    "意",
    " ",
    "2",
    ",",
    "6",
    "1",
    "6",
    ",",
    "0",
    "1",
    "7",
    " ",
    "股",
    "，",
    "占",
    "出",
    "席",
    "会",
    "议",
    "中",
    "小",
    "股",
    "东",
    "所",
    "持",
    "股",
    "份",
    "的",
    " ",
    "6",
    "9",
    ".",
    "8",
    "2",
    "2",
    "0",
    "%",
    "；",
    "反",
    "对",
    " ",
    "1",
    ",",
    "1",
    "3",
    "0",
    ",",
    "6",
    "7",
    "5",
    " ",
    "股",
    "，",
    "占",
    "出",
    "席",
    "会",
    "议",
    "中",
    "小",
    "股",
    "东",
    "所",
    "持",
    "股",
    "份",
    "的",
    " ",
    "3",
    "0",
    ".",
    "1",
    "7",
    "8",
    "0",
    "%",
    "；",
    "弃",
    "权",
    " ",
    "0",
    " ",
    "股",
    "。"
  ],
  "entity": [],
  "relation": [],
  "event": [
    {
      "type": "股东增持",
      "text": "增资",
      "offset": [
        140,
        141
      ],
      "args": [
        {
          "text": "巨人网络",
          "type": "增持方",
          "offset": [
            0,
            1,
            2,
            3
          ]
        },
        {
          "text": "巨堃网络",
          "type": "股票简称",
          "offset": [
            10,
            11,
            12,
            13
          ]
        }
      ]
    },
    {
      "type": "股东增持",
      "text": "增资",
      "offset": [
        140,
        141
      ],
      "args": [
        {
          "text": "巨堃网络",
          "type": "股票简称",
          "offset": [
            10,
            11,
            12,
            13
          ]
        }
      ]
    },
    {
      "type": "股东增持",
      "text": "增资",
      "offset": [
        140,
        141
      ],
      "args": [
        {
          "text": "巨堃网络",
          "type": "股票简称",
          "offset": [
            10,
            11,
            12,
            13
          ]
        }
      ]
    }
  ],
  "schema": "DUEE_FIN_LITE",
  "spot_asoc": [
    {
      "span": "增资",
      "label": "股东增持",
      "asoc": [
        [
          "增持方",
          "巨人网络"
        ],
        [
          "股票简称",
          "巨堃网络"
        ],
        [
          "股票简称",
          "巨堃网络"
        ],
        [
          "股票简称",
          "巨堃网络"
        ]
      ]
    }
  ],
  "spot": [
    "股东增持"
  ],
  "asoc": [
    "增持方",
    "股票简称",
    "每股交易价格",
    "增持部分占所持比例",
    "披露时间",
    "增持部分占总股本比例",
    "交易股票/股份数量",
    "交易金额",
    "交易完成时间"
  ]
}

对比下英文的只是缺少 "record" 这个字段  这个需要如何用代码自动生成 

当前的报错信息

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_seq2seq.py", line 726, in <module>
    main()
  File "run_seq2seq.py", line 514, in main
    features=RecordFeature,
  File "/root/anaconda3/envs/py3712/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 173     6, in map
    transformed_shards = [r.get() for r in results]
  File "/root/anaconda3/envs/py3712/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 173     6, in <listcomp>
    transformed_shards = [r.get() for r in results]
  File "/root/anaconda3/envs/py3712/lib/python3.7/site-packages/multiprocess/pool.py", line 657, in      get
    raise self._value
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenize     d example) or `List[List[str]]` (batch of pretokenized examples).
```

**Comment by xxllp** [comment]
我用中文的数据集 在数据集上的预测结果基本都是空 这种是为啥原因呢

**Comment by luyaojie** [comment]
可以简单贴一下运行方式吗？或者附一下文件作为附件

**Comment by xxllp** [comment]
这个日志里面会报很多如下提升 
```
05/13/2022 21:28:09 - WARNING - uie.extraction.predict_parser.spotasoc_predict_parser -   Fix gold: 【 【 质押 <extra_id_5> 质押 【 质押物所属公司 <extra_id_5> 天舟文化 】 【 质押物所属公司 <extra_id_5> 天舟文化 】 【 质押物所属公司 <extra_id_5> 天舟文化 】 【 质押物所属公司 <extra_id_5> 天舟文化 】 【 质押方 <extra_id_5> 袁雄贵 】 【 质押方 <extra_id_5> 袁雄贵 】 【 质押方 <extra_id_5> 袁雄贵 】 【 质押股票/股份数量 <extra_id_5> 0 】 【 披露时间 <extra_id_5> 9月30日 】 【 披露时间 <extra_id_5> 9月30日 】 【 披露时间 <extra_id_5> 9月30日 】 【 披露时间 <extra_id_5> 9月30日 】 【 质押方 <extra_id_5> 樟树市悦玩投资管理中心(有限合伙) 】 【 质押物 <extra_id_5> 股票 】 【 质押股票/股份数量 <extra_id_5> 400万 】 【 事件时间 <extra_id_5> 截止目前 】 【 事件时间 <extra_id_5> 截止目前 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押股票/股份数 】 】 】
05/13/2022 21:28:09 - WARNING - uie.extraction.predict_parser.spotasoc_predict_parser -   Ill gold: 【  【 质押 <extra_id_5> 质押 【 质押物所属公司 <extra_id_5> 宝馨科技 】  【 质押物所属公司 <extra_id_5> 宝馨科技 】  【 质押物所属公司 <extra_id_5> 宝馨科技 】  【 质押物所属公司 <extra_id_5> 宝馨科技 】  【 质押方 <extra_id_5> 陈东 】  【 质押方 <extra_id_5> 陈东 】  【 质押方 <extra_id_5> 陈东 】  【 质押物 <extra_id_5> 股份 】  【 质押物 <extra_id_5> 股份 】  【 质押物 <extra_id_5> 股份 】  【 质押物 <extra_id_5> 股份 】  【 披露时间 <extra_id_5> 8月13日 】  【 披露时间 <extra_id_5> 8月13日 】  【 披露时间 <extra_id_5> 8月13日 】  【 披露时间 <extra_id_5> 8月13日 】  【 质押股票/股份数量 <extra_id_5> 1,390万 】  【 质押物占持股比 <extra_id_5> 11.64% 】  【 事件时间 <extra_id_5> 截至本公告日 】  【 事件时间 <extra_id_5> 截至本公告日 】  【 事件时间 <extra_id_5> 截至本公告日 】  【 质押股票/股份数量 <extra_id_5> 11,894万 】  【 质押物占总
05/13/2022 21:28:09 - WARNING - uie.extraction.predict_parser.spotasoc_predict_parser -   Fix gold: 【 【 质押 <extra_id_5> 质押 【 质押物所属公司 <extra_id_5> 宝馨科技 】 【 质押物所属公司 <extra_id_5> 宝馨科技 】 【 质押物所属公司 <extra_id_5> 宝馨科技 】 【 质押物所属公司 <extra_id_5> 宝馨科技 】 【 质押方 <extra_id_5> 陈东 】 【 质押方 <extra_id_5> 陈东 】 【 质押方 <extra_id_5> 陈东 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 披露时间 <extra_id_5> 8月13日 】 【 披露时间 <extra_id_5> 8月13日 】 【 披露时间 <extra_id_5> 8月13日 】 【 披露时间 <extra_id_5> 8月13日 】 【 质押股票/股份数量 <extra_id_5> 1,390万 】 【 质押物占持股比 <extra_id_5> 11.64% 】 【 事件时间 <extra_id_5> 截至本公告日 】 【 事件时间 <extra_id_5> 截至本公告日 】 【 事件时间 <extra_id_5> 截至本公告日 】 【 质押股票/股份数量 <extra_id_5> 11,894万 】 【 质押物占总 】 】 】
05/13/2022 21:28:09 - WARNING - uie.extraction.predict_parser.spotasoc_predict_parser -   Ill gold: 【  【 质押 <extra_id_5> 质押 【 质押物所属公司 <extra_id_5> 证通电子 】  【 质押物所属公司 <extra_id_5> 证通电子 】  【 质押物所属公司 <extra_id_5> 证通电子 】  【 质押物所属公司 <extra_id_5> 证通电子 】  【 质押方 <extra_id_5> 曾胜强 】  【 质押方 <extra_id_5> 曾胜强 】  【 质押股票/股份数量 <extra_id_5> 0 】  【 质押股票/股份数量 <extra_id_5> 540万 】  【 披露时间 <extra_id_5> 7月15日晚间 】  【 披露时间 <extra_id_5> 7月15日晚间 】  【 披露时间 <extra_id_5> 7月15日晚间 】  【 披露时间 <extra_id_5> 7月15日晚间 】  【 质押物 <extra_id_5> 股份 】  【 质押物 <extra_id_5> 股份 】  【 质押物 <extra_id_5> 股份 】  【 质押物 <extra_id_5> 股份 】  【 质押物占持股比 <extra_id_5> 0% 】  【 事件时间 <extra_id_5> 2020年7月9日 】  【 质押物占持股比 <extra_id_5> 5.16% 】  【 事件时间 <extra_id_5> 截至本公告日 】  【 事件时间 <extra_id_5> 截至本公告
05/13/2022 21:28:09 - WARNING - uie.extraction.predict_parser.spotasoc_predict_parser -   Fix gold: 【 【 质押 <extra_id_5> 质押 【 质押物所属公司 <extra_id_5> 证通电子 】 【 质押物所属公司 <extra_id_5> 证通电子 】 【 质押物所属公司 <extra_id_5> 证通电子 】 【 质押物所属公司 <extra_id_5> 证通电子 】 【 质押方 <extra_id_5> 曾胜强 】 【 质押方 <extra_id_5> 曾胜强 】 【 质押股票/股份数量 <extra_id_5> 0 】 【 质押股票/股份数量 <extra_id_5> 540万 】 【 披露时间 <extra_id_5> 7月15日晚间 】 【 披露时间 <extra_id_5> 7月15日晚间 】 【 披露时间 <extra_id_5> 7月15日晚间 】 【 披露时间 <extra_id_5> 7月15日晚间 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物 <extra_id_5> 股份 】 【 质押物占持股比 <extra_id_5> 0% 】 【 事件时间 <extra_id_5> 2020年7月9日 】 【 质押物占持股比 <extra_id_5> 5.16% 】 【 事件时间 <extra_id_5> 截至本公告日 】 【 事件时间 <extra_id_5> 截至本公告 】 】 】

我放大了参数里面的 max_source_length  max_target_length 现在结果看起来有些正常了

**Comment by xxllp** [comment]
python run_seq2seq.py \
    --do_train --do_eval --do_predict  \
    --use_fast_tokenizer=True \
    --ddp_find_unused_parameters=False \
    --predict_with_generate \
    --evaluation_strategy=epoch \
    --save_strategy=epoch \
    --metric_for_best_model eval_overall-F1 \
    --save_total_limit 1 \
    --load_best_model_at_end \
    --max_source_length=500 \
    --max_prefix_length=-1 \
    --max_target_length=256\
    --num_train_epochs=30 \
    --task=meta \
    --train_file=dataset/DUEE_FIN_LITE/train1.json \
    --validation_file=dataset/DUEE_FIN_LITE/val1.json \
    --test_file=dataset/DUEE_FIN_LITE/val1.json \
    --record_schema=dataset/DUEE_FIN_LITE/record.schema \
    --per_device_train_batch_size=8 \
    --per_device_eval_batch_size=8 \
    --output_dir=output\
    --logging_dir=log \
    --model_name_or_path=hf_models/uie-char-small/ \
    --learning_rate=3e-4 \
    --source_prefix=meta \
    --lr_scheduler_type=linear \
    --label_smoothing_factor=0\
    --eval_steps 0 \
    --decoding_format spotasoc \
    --warmup_ratio 0.06 \
    --preprocessing_num_workers=4 \
    --dataloader_num_workers=0 \
    --meta_negative=-1 \
    --meta_positive_rate=1 \
    --skip_memory_metrics \
    --no_remove_unused_columns \
    --ordered_prompt=True \
    --save_better_checkpoint=False \
    --start_eval_step=0 \
    --spot_noise=0.1 \
    --asoc_noise=0.1 \
    --seed=234

**Comment by luyaojie** [comment]
日志中的WARNING输出是输出的目标结构过长导致，因为训练的时候卡了最大长度。
预测结果基本都是空，应该是输入的prefix过长导致，在该数据集上使用可以将 --max_prefix_length 设置为0；或者参考Paddle的基线，按照事件类型拆分数据集。
