### ISSUE TITLE
应用的一些疑问

### ISSUE THREAD

**Issue by Zhongzh17** [universal-ie/UIE#9]
你好，有些疑问请教一下。

在中文的关系抽取数据集进行使用，数据集的关系类型包括下面的类型（共17个）：
[
'<spot>人物<asoc>毕业院校<asoc>父亲<asoc>母亲<asoc>妻子<asoc>丈夫<asoc>祖籍<asoc>国籍', 
'<spot>电视综艺<asoc>嘉宾<asoc>主持人', 
'<spot>娱乐人物<asoc>配音<asoc>获奖<asoc>饰演', 
'<spot>影视作品<asoc>主题曲<asoc>上映时间<asoc>票房<asoc>编剧<asoc>制片人<asoc>改编自<asoc>出品公司<asoc>导演<asoc>主演', 
'<spot>企业/品牌<asoc>代言人', 
'<spot>歌曲<asoc>所属专辑<asoc>歌手<asoc>作词<asoc>作曲', 
'<spot>图书作品<asoc>作者', 
'<spot>学科专业<asoc>专业代码<asoc>修业年限', 
'<spot>机构<asoc>占地面积<asoc>成立日期<asoc>简称', 
'<spot>行政区<asoc>邮政编码<asoc>气候<asoc>面积<asoc>人口数量', 
'<spot>企业<asoc>注册资本<asoc>创始人<asoc>总部地点<asoc>董事长', 
'<spot>文学作品<asoc>主角', 
'<spot>学校<asoc>校长', 
'<spot>国家<asoc>首都<asoc>官方语言', 
'<spot>历史人物<asoc>朝代<asoc>号', 
'<spot>景点<asoc>所在城市', 
'<spot>地点<asoc>海拔'
]

如果ssi是包括所有关系类型，那么ssi就是
ssi_all = '<spot>人物<spot>电视综艺<spot>娱乐人物<spot>影视作品<spot>企业/品牌<spot>歌曲<spot>图书作品<spot>学科专业<spot>机构<spot>行政区<spot>企业<spot>文学作品<spot>学校<spot>国家<spot>历史人物<spot>景点<spot>地点<asoc>毕业院校<asoc>父亲<asoc>母亲<asoc>妻子<asoc>丈夫<asoc>祖籍<asoc>国籍<asoc>嘉宾<asoc>主持人<asoc>配音<asoc>获奖<asoc>饰演<asoc>主题曲<asoc>上映时间<asoc>票房<asoc>编剧<asoc>制片人<asoc>改编自<asoc>出品公司<asoc>导演<asoc>主演<asoc>代言人<asoc>所属专辑<asoc>歌手<asoc>作词<asoc>作曲<asoc>作者<asoc>专业代码<asoc>修业年限<asoc>占地面积<asoc>成立日期<asoc>简称<asoc>邮政编码<asoc>气候<asoc>面积<asoc>人口数量<asoc>注册资本<asoc>创始人<asoc>总部地点<asoc>董事长<asoc>主角<asoc>校长<asoc>首都<asoc>官方语言<asoc>朝代<asoc>号<asoc>所在城市<asoc>海拔'

如果只包括句子中出现的ssi，那么对与下面的句子
‘1、李炳照，王宏洲. 大学数学，北京：清华大学出版社，2011.08；’ ，其中只包含“<spot>图书作品<asoc>作者”关系，其对应的
ssi = '<spot>图书作品<asoc>作者'

我的疑问主要是：
1. 训练和预测的时候，分别采用什么样的ssi，看论文好像预训练不是用的ssi_all的形式，而finetune用的是ssi_all的形式。如果不是用全部的ssi，预测时，是不是需要把各个ssi依次跟句子拼接，依次进行预测呢？（比如上面的关系抽取，有17个关系类型，对与一个句子，一共需要预测17次）
2. 论文中的负样本是在SEL（也就是期望模型生成的结果）中添加NULL，这种方式训练出来的模型，如果输入一个没有任何预期结果的句子，可以保证预测出来全是NULL吗？
3. ssi实际起到什么作用？如果只在某个数据集上进行finetune训练，而不进行多种任务同时训练，不添加ssi是否可行？

**Comment by luyaojie** [comment]
你好，相关疑问回答如下：

1. 预训练中采用的是句子中出现的ssi加上采样的负例；下游任务finetune采用的ssi_all。预测的时候只要和finetune的训练方式一致即可，即如果用的全部ssi_all 就使用ssi_all 进行预测；使用单个关系类型finetune，预测时就拆成多个预测。
2. 自动添加NULL构造的负样本是指特定于拒绝识别机制的负样本；信息抽取的负样本应该是句子不包含需要抽取信息样本，实际输出结果为`()`，即空。
3.  ssi主要起到约束输出空间、引导生成的作用。在单个数据集上使用，不添加SSI也可行，相当于学习一个特定任务的结构生成。

**Comment by Zhongzh17** [comment]
谢谢解答，另外还有2个疑问。

1. 预训练时，句子中采用的ssi是正例+采样的负例，那么采样的负例是否需要在答案中体现？
   以实体抽取为例，假设实体抽取数据集里面包含【”人名“、”机构“、”地址“】，对于下面的句子，
   ”谷爱凌在2022年冬奥会取得了自由式滑雪冠军“，其中只有”人名“类型。假设ssi中采样了”机构“类型作为负样，即
   ssi = ”[spot]人名[spot]机构[text]“
   预训练时以下哪种数据形式：
   1）模型输入：”[spot]人名[spot]机构[text]谷爱凌在2022年冬奥会取得了自由式滑雪冠军“
         模型输出：“((人名: 谷爱凌))”
   2) 模型输入：”[spot]人名[spot]机构[text]谷爱凌在2022年冬奥会取得了自由式滑雪冠军“
        模型输出：“((人名: 谷爱凌)(机构: null))”
   亦或者是其他数据形式。就是说，ssi中有负样实体了，输出中是否需要体现出负样实体？

2. 在微调时，对没有预期输出的句子（以实体抽取为例，就是不包含任何实体类型的句子）希望预测为空，那训练数据中是否必须要有信息抽取的负样本？还是以上面的实体抽取为例。
   模型输入：”[spot]人名[spot]机构[spot]地址[text]今天天气挺好的“
   模型输出：”()“

**Comment by luyaojie** [comment]
1. 目前添加在 README.md 模型是没有添加拒绝识别噪声的，但是可以直接在参数 `spot_noise` 和 `asoc_noise` 中添加。
2. 需要的，我的实验保留了数据的原始分布，没有丢弃或者采样信息抽取的负例。

**Comment by Zhongzh17** [comment]
谢谢解答！
